### ISSUE TITLE
check: Verify arguments and attributes are listed in alphabetical order

### ISSUE THREAD

**Issue by anGie44** [bflad/tfproviderdocs#39]
Would be nice to help readability by sorting arguments and attributes listed in a resource/data-source documentation. Additional handling might be with block attributes where we generally define them and their nested attributes in a sub-heading outside of the bullet point lists.

**Comment by bflad** [comment]
Experimental support for this has been added via new `-enable-contents-check` and `-require-schema-ordering` flags in version 0.8.0 of tfproviderdoc. Please note that this only supports the "top" arguments/attribute lists and not sub-sections at the current time.

**Comment by bflad** [comment]
This project will be archived in preference of the revamped `validate` command in github.com/hashicorp/terraform-plugin-docs implementing much of the basic validation logic from this project. Feature requests should be submitted over there at this point.
