### ISSUE TITLE
Document section detection is too greedy

### ISSUE THREAD

**Issue by gdavison** [bflad/tfproviderdocs#49]
When using `-enable-contents-check`, the section detector only looks for a match at the start of the section header.

For example, a heading like `## Imported Certificates` will trigger an error, even when there's a section `## Import` later in the document.

Several possible solutions could be used:

1. Adding a comment to ignore a rule
2. Only trigger a header rule if there's no exactly matching header in the document
3. Content analysis on the body of the section, especially for sections like `Import` which have a standard format

**Comment by bflad** [comment]
This project will be archived in preference of the revamped `validate` command in github.com/hashicorp/terraform-plugin-docs implementing much of the basic validation logic from this project. Bug reports and feature requests should be submitted over there at this point.
